name: docker-build
on: push
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jcdelarosa7
          password: dckr_pat_DDRuMpd3wlzZurLxG2l265Td_1U
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker build . --file Dockerfile --tag jcdel:$(date +%m-%d-%y)
           docker tag jcdel:$(date +%m-%d-%y) jcdel:first
           docker push jcdel:$(date +%m-%d-%y)
