name: docker-build
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
             path: anybadge
             Dockerfile: anybadge/Dockerfile.txt
             docker build . --file Dockerfile --tag myapp
