name: docker-build
on: push
jobs:
  my-job:
    runs: ubuntu-latest
      using: 'docker'
      image: 'Dockerfile'
    steps:
      - name: my-step
        run: |
             ls -lha ../ 
             docker build -t my-apache2 ../.
