name: docker-build
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
          registry: https://hub.docker.com/
          username: jcdelarosa7
          password: dckr_pat_cByD2ViVpMSHCdRAql4l4EMsGpc
    - uses: actions/checkout@v2
    - run: |
           docker build . --file Dockerfile --tag jcdel:$(date +%m-%d-%y)
           docker tag jcdel:$(date +%m-%d-%y) jcdel:first
           docker push jcdel:$(date +%m-%d-%y)
