name: docker-build
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        working-directory: anybadge
        run: |
             docker build . --file Dockerfile --tag myapp
